apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../kafka-benchmark.yaml
  - ingest-hpa.yaml
patches:
  - target:
      group: monitoring.coreos.com
      version: v1
      kind: ServiceMonitor
      name: ingest
      namespace: kafka-benchmark
    patch: |-
      $patch: delete
      apiVersion: monitoring.coreos.com/v1
      kind: ServiceMonitor
      metadata:
        name: ingest
        namespace: kafka-benchmark
  - target:
      group: monitoring.coreos.com
      version: v1
      kind: ServiceMonitor
      name: consumer
      namespace: kafka-benchmark
    patch: |-
      $patch: delete
      apiVersion: monitoring.coreos.com/v1
      kind: ServiceMonitor
      metadata:
        name: consumer
        namespace: kafka-benchmark
