apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-benchmark
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: baro-apps
  source:
    repoURL: https://github.com/yuminn-k/k8s-monitoring.git
    targetRevision: main
    path: gitops/kafka-benchmark
  destination:
    name: in-cluster
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true
      - CreateNamespace=false
