apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources/kafka-benchmark.yaml
images:
  - name: k8s-monitoring-lab
    newName: ghcr.io/yuminn-k/baro
    newTag: sha-735cb1474447cd556585da36f7463f89614932a8
