apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources/kafka-benchmark.yaml
images:
  - name: k8s-monitoring-lab
    newName: ghcr.io/yuminn-k/baro
    newTag: sha-d43556da9046788e07c17e1d887766a0f37c791e
