apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources/kafka-benchmark.yaml
images:
  - name: k8s-monitoring-lab
    newName: ghcr.io/yuminn-k/k8s-monitoring
    newTag: sha-b72a8124fa1c38ff4b3e029fadb0238da79c7dc0
