apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: benchmark-consumer-lag
  namespace: kafka-benchmark
spec:
  scaleTargetRef:
    name: consumer
  pollingInterval: 10
  cooldownPeriod: 60
  minReplicaCount: 1
  maxReplicaCount: 5
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 60
          selectPolicy: Max
          policies:
            - type: Percent
              value: 50
              periodSeconds: 60
  triggers:
    - type: kafka
      metadata:
        bootstrapServers: kafka.kafka-benchmark.svc.cluster.local:9092
        consumerGroup: benchmark-consumers
        topic: benchmark-events
        lagThreshold: "50"
        activationLagThreshold: "10"
        offsetResetPolicy: latest
        scaleToZeroOnInvalidOffset: "false"
