apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources/workload.yaml
  - resources/alert-receiver.yaml
images:
  - name: k8s-monitoring-lab
    newName: ghcr.io/yuminn-k/k8s-monitoring
    newTag: sha-2b018671a4b16dfc14fb02d12b0e45aa5576d4bf
