apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources/workload.yaml
  - resources/alert-receiver.yaml
images:
  - name: k8s-monitoring-lab
    newName: ghcr.io/yuminn-k/k8s-monitoring
    newTag: sha-fe1fac7ca7800ab276d434fda96ed1abfa8492b2
